macro(enable_ipo)
    include(CheckIPOSupported)

    check_ipo_supported(RESULT result OUTPUT output)
    if(result)
    message("ipo enabled")
        set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
    else()
        message(SEND_ERROR "IPO not supported: ${output}")
    endif()
endmacro()